service: greeting
# app and org for use with dashboard.serverless.com
app: my-aws-node-rest-api-app
#org: your-org-name

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
  stage: dev
  region: ap-south-1


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /v1/testIP
          method: get
